[workspace]
[package]
version = "0.1.0"
name = "sha3-bench"
edition = "2021"

[dependencies]
sp1-zkvm = "=4.1.1"
risc0-zkvm = { version = "1.2.3", default-features = false, features = ["std"] }
sha3 = { version = "0.10.8", default-features = false }

[features]
risc0 = []
sp1 = []
