[workspace]
[package]
name = "c"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
libc = "0.2.170"
risc0-zkvm = { version = "1.2.3", default-features = false, features = ["std"] }
sp1-zkvm = "=4.1.1"

[build-dependencies]
cc = "1.2.16"

[features]
risc0 = []
sp1 = []
