[package]
name = "c-sample"
version = "0.1.0"
edition = "2021"

[dependencies]
risc0-zkvm = { version = "=1.2.3", default-features = false, features = ["std"] }
sp1-zkvm = "=4.1.1"
printf-compat = { version = "0.1", default-features = false }

[features]
risc0 = []
sp1 = []
