[workspace]
[package]
name = "polybench-2mm"
version = "0.1.0"
edition = "2021"

[dependencies]
sp1-zkvm = "=4.1.1"
risc0-zkvm = { version = "1.2.3", default-features = false, features = ["std"] }
polybench-rs = { path = "../polybench" }

[features]
risc0 = []
sp1 = []
